services:
  # 1. The Load Balancer (Entry Point)
  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

  # 2. Your Django App
  backend:
    build:
      context: ./backend
    command: gunicorn --bind 0.0.0.0:8000 src.wsgi:application
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - REDIS_URL=redis://redis:6379/1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,backend
      - CORS_ALLOWED_ORIGINS=http://localhost,http://localhost:3000
      - CSRF_TRUSTED_ORIGINS=http://localhost,http://localhost:3000
      - DJANGO_SETTINGS_MODULE=settings.prod
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  # 3. Next.js Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost/api
    depends_on:
      - backend

  # 4. The Database (Postgres)
  db:
    image: postgres:15-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 5. The Cache (Redis)
  redis:
    image: redis:7-alpine
    restart: always

  # 6. Celery Worker (Optional)
  # celery:
  #   build:
  #     context: ./backend
  #   command: celery -A src worker --loglevel=info
  #   env_file:
  #     - ./backend/.env
  #   environment:
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_HOST=db
  #     - REDIS_URL=redis://redis:6379/1
  #     - CELERY_BROKER_URL=redis://redis:6379/0
  #     - CELERY_RESULT_BACKEND=redis://redis:6379/0
  #     - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
  #     - DJANGO_SETTINGS_MODULE=settings.prod
  #   depends_on:
  #     - backend
  #     - redis

volumes:
  postgres_data:
